ArchiveMVC5/Controllers/ViewController.cs
using ArchiveMVC5.Controllers;
using ArchiveMVC5.Models;
using ArchiveMVC5.Models.DataProvider;
using ArchiveMVC5.Utility;
using log4net;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArchiveMVC5.Controllers
{
    public class ViewController : BaseController
    {
        public ActionResult Index(Guid id, bool partal = false)
        {
            DocumentModel doc = null;
            DocumentProvider docProvider = new DocumentProvider(Utilities.UserName, Utilities.Password);
            PermissionProvider pp = new PermissionProvider(Utilities.UserName, Utilities.Password);

            if(Utilities.OpenedDocuments.SingleOrDefault(p=> p.Id == id) != null)
            {
                doc = Utilities.OpenedDocuments.SingleOrDefault(p=> p.Id == id);
            }
            else
            {
                doc = docProvider.GetDocument(id);
                Utilities.OpenedDocuments.Add(doc);
            }

            Utilities.OpenningDocument = doc;

            if (doc != null && !doc.DocumentType.DocumentTypePermission.AllowedSearch)
            {
                ViewData[Constant.KEY_ERROR] = true;
                return View();
            }
            ViewData[Constant.KEY_ANOTATION_PERMISSION] = doc.DocumentType.AnnotationPermission;
            ViewData[Constant.KEY_DOCTYPE_PERMISSION] = doc.DocumentType.DocumentTypePermission;
            //Init param to cache
            var cTime = DateTime.Now.AddMinutes(24 * 3600);
            var cExp = System.Web.Caching.Cache.NoSlidingExpiration;
            var keyCache = Guid.NewGuid().ToString();
            List<CacheFileResult> list = new List<CacheFileResult>();
            var sortedPages = doc.Pages.OrderBy(row => row.PageNumber).ToList();
            var Pages = new List<dynamic>();
            foreach (var page in sortedPages)
            {
                dynamic p = new ExpandoObject();
                p.Width = page.Width;
                List<AnnotationModel> anno = new List<AnnotationModel>();
                var contentType = MimeMap.ContentTypeFromExtension(page.FileExtension);
                var b = page.FileBinaries;
                if (b == null)
                    return View();

                page.FileType = Utilities.GetFileType(page.FileExtension);
                p.FileType = page.FileType;
                //Cache Page
                //Page trong DB neu la TIFF thi cung da dc split de luu vao
                //Do do result tra ve sau khi CacheFile thuc su chi co 1 element
                if (page.Annotations != null && page.FileType == FileTypeModel.Image)
                {
                    var img = ProcessImages.ByteArrayToImage(page.FileBinaries);
                    img = ProcessImages.Rotate(img, (int)page.RotateAngle);
                    foreach (var a in page.Annotations)
                    {
                        if (a.Type == AnnotationTypeModel.Redaction &&
                            !doc.DocumentType.AnnotationPermission.AllowedHideRedaction)
                        {
                            a.Left *= img.Width / page.Width;
                            a.Top *= img.Width / page.Width;
                            a.Width *= img.Width / page.Width;
                            a.Height *= img.Width / page.Width;
                            img = ProcessImages.AddAnnotation(img, a);
                        }
                        else if ((a.Type == AnnotationTypeModel.Highlight
                                    && doc.DocumentType.AnnotationPermission.AllowedSeeHighlight)
                             || (a.Type == AnnotationTypeModel.Text
                                    && doc.DocumentType.AnnotationPermission.AllowedSeeText)
                             || (a.Type == AnnotationTypeModel.Redaction
                                    && doc.DocumentType.AnnotationPermission.AllowedHideRedaction))
                        {
                            double angle = -1 * page.RotateAngle * Math.PI / 180;
                            anno.Add(a);
                        }
                    }
                    b = ProcessImages.ImageToByteArray(ProcessImages.Rotate(img, (int)(360 - page.RotateAngle)));
                    p.RotateAngle = page.RotateAngle;
                    p.Annotations = anno;
                }
                var lst = CacheHelper.CacheFile(MimeMap.ContentTypeFromExtension(page.FileExtension),
                                                b, page.OriginalFileName, Server.MapPath("~/Temp"));
                p.Info = lst.First();
                p.PageId = page.Id;
                Pages.Add(p);
            }

            foreach (var field in doc.DocumentType.Fields)
            {
                if (doc.FieldValues.FirstOrDefault(p => p.Field.Id == field.Id) == null)
                {
                    var fieldValue = new FieldValueModel { Field = field, Value = field.DefaultValue };

                    if (field.DataType == Ecm.Domain.FieldDataType.Date && field.UseCurrentDate)
                    {
                        fieldValue.Value = DateTime.Now.ToShortDateString();
                    }

                    doc.FieldValues.Add(fieldValue);
                }
            }

            ViewData[Constant.KEY_PAGE_LIST] = Pages;

            TempData[Constant.KEY_FIELDS_VALUE] = doc.FieldValues;
            ViewData[Constant.KEY_DOCUMENT_ID] = doc.Id;
            ViewData[Constant.KEY_DOCUMENT_NAME] = doc.DocumentType.Name;
            
            if (partal)
                return PartialView();
            return View();
        }

        public ActionResult GetHtml(String key)
        {
            CacheTemporaryFile file = (CacheTemporaryFile)System.Web.HttpContext.Current.Cache[key];
            if (file != null && file.FileName != null)
            {
                var _path = "~/Temp/" + System.IO.Path.GetFileName(file.FileName);
                ViewData["PATH"] = _path;
            }
            return PartialView();
        }

        public ActionResult GetDocument(string key)
        {
            CacheTemporaryFile file = (CacheTemporaryFile)System.Web.HttpContext.Current.Cache[key];
            if (file != null && file.FileName != null)
            {
                var path = "~/Temp/" + System.IO.Path.GetFileName(file.FileName);
                var filename = file.OrginalFileName;
                if (filename.Contains("pdf") || filename.Contains("PDF"))
                {
                    ViewData["FILE_TYPE"] = "PDF";
                }
                ViewData["PATH"] = path;

            }
            return PartialView();
        }

        public FileStreamResult ViewPdf(string path)
        {
            if (!String.IsNullOrEmpty(path))
            {
                FileStream result = new FileStream(Server.MapPath(path), FileMode.Open, FileAccess.Read);
                return File(result, "application/pdf");
            }
            else
            {
                return null;
            }
        }

        public ActionResult Download(Guid docId, int pageId)
        {
            try
            {
                DocumentProvider docProvider = new DocumentProvider(Utility.Utilities.UserName, Utility.Utilities.Password);
                var doc = docProvider.GetDocument(docId);
                var page = doc.Pages[pageId];
                byte[] binaries = page.FileBinaries;
                return File(binaries, MimeMap.ContentTypeFromExtension(page.FileExtension), page.OriginalFileName);
            }
            catch(Exception ex) {
                ExceptionLog(ex, ex.Message);
            }
            //File not found
            return View();
        }

        public ActionResult ImageViewer(string key)
        {
            CacheObject image = (CacheObject)System.Web.HttpContext.Current.Cache[key];
            if (typeof(CacheImage).Equals(image.GetType()))
            {
                ViewData["ImageKey"] = key;
                return PartialView();
            }
            return RedirectToAction("Index", "Login");
        }

        public class DocumentCaching
        {
            public DocumentModel Document { set; get; }
            public string IconKey { set; get; }
            public List<string> ImagePageKey { set; get; }
        }

        public ActionResult GetFieldValues(DocumentSerializable doc)
        {
            if (TempData[Constant.KEY_FIELDS_VALUE] != null)
            {
                return PartialView("OCR", (List<FieldValueModel>)TempData[Constant.KEY_FIELDS_VALUE]);
            }

            return null;
        }

        public ActionResult LoadToolbar(string id)
        {
            DocumentTypeProvider provider = new DocumentTypeProvider(Utilities.UserName, Utilities.Password);

            if (id != string.Empty)
            {
                Guid docTypeId = Guid.Parse(id);
                //var docType = Utilities.CaptureDocumentTypes.Where(d => d.Id == docTypeId).First();
                var docType = provider.GetCapturedDocumentTypes().Where(d => d.Id == docTypeId).First();
                if (docType != null)
                {
                    ViewData[Constant.KEY_ANOTATION_PERMISSION] = docType.AnnotationPermission;
                    ViewData[Constant.KEY_DOCTYPE_PERMISSION] = docType.DocumentTypePermission;
                }
            }
            else
            {
                ViewData[Constant.KEY_ANOTATION_PERMISSION] = null;
                ViewData[Constant.KEY_DOCTYPE_PERMISSION] = null;
            }

            return PartialView("Toolbar");
        }

        public ActionResult LoadTableFieldValue(DocumentFieldValueSerializable para)
        {
            FieldValueModel fieldValue = new FieldValueModel();
            DocumentProvider documentProvider = new DocumentProvider(Utilities.UserName, Utilities.Password);

ArchiveMVC5/Views/Search/AddMoreCondition.cshtml
@model ArchiveMVC5.Models.SearchModel
@{
    var Doctype = Model.ListDocType.Where(p => p.Id == Model.DocumentTypeId).FirstOrDefault();
    
    var idComboboxOperator = ArchiveMVC5.Utility.UniqueId.GetUniqueKey();
    var idComboboxValue = ArchiveMVC5.Utility.UniqueId.GetUniqueKey();
    }
<div class="col-md-12 additionalCondition">
    <div class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
        <select id="Conjunction" class="form-control input-sm">
            @foreach (Ecm.Domain.SearchConjunction dataType in Enum.GetValues(typeof(Ecm.Domain.SearchConjunction)))
            {
                <option value="@((int)dataType)">@dataType.ToString()</option>
        }
        </select>
    </div>
    <div class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
        <select  id="FieldName" onchange="CreateComboboxOperator(this.value,'@idComboboxOperator','@(idComboboxValue)')" class="form-control input-sm">
            @foreach (var item in Doctype.Fields)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <input type="hidden" value="@Model.DataTypeJson" id="fieldDataType" />
    </div>
    <div id="@(idComboboxOperator)" class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
        <select id="Operator" onchange="CreateTextBoxValue(this.value,'@(Doctype.Fields.FirstOrDefault().Id)','@idComboboxValue')" class="form-control input-sm">
            @{
                var listOperator = ArchiveMVC5.Utility.GeneratorJson.GetOperatorFromType(Doctype.Fields.FirstOrDefault().DataType);
            }
            @foreach (var item1 in listOperator)
            {                                
                <option value="@((int)item1)">@item1</option>
            }

        </select>
    </div>
    <div id="@(idComboboxValue)" class="form-group col-md-5" style="margin-bottom: 1px !important;padding-left: 1px !important;">
        @Html.Raw(ArchiveMVC5.Utility.GeneratorJson.GetComboBoxValue(Doctype.Fields.FirstOrDefault(), listOperator.First(), "", ""))
    </div>
    <div class="form-group col-md-1 delete-new" style="margin-bottom: 1px !important; padding-left:0px !important">
        <a role="button" class="btn btn-xs btn-danger">
            <i class="glyphicon glyphicon glyphicon glyphicon-trash"></i>
        </a>
    </div>
    </div>

ArchiveMVC5/Views/Search/AdvanceSearchCondition.cshtml
@model ArchiveMVC5.Models.SearchQueryModel
@if (Model.DocumentType != null)
{
    foreach (var item in Model.DocumentType.Fields.Where(p => !p.IsSystemField))
    {
        var value1 =  Model.SearchQueryExpressions.FirstOrDefault(p=> p.Field.Id == item.Id) == null ? "" : Model.SearchQueryExpressions.FirstOrDefault(p=> p.Field.Id == item.Id).Value1;
        var value2 =  Model.SearchQueryExpressions.FirstOrDefault(p=> p.Field.Id == item.Id) == null ? "" : Model.SearchQueryExpressions.FirstOrDefault(p=> p.Field.Id == item.Id).Value2;

    <div class="col-md-12" data-fieldid="@item.Id">
        <div class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
            <select id="Conjunction" class="form-control input-sm">
                @foreach (Ecm.Domain.SearchConjunction dataType in Enum.GetValues(typeof(Ecm.Domain.SearchConjunction)))
                {
                    <option value="@((int)dataType)">@dataType.ToString()</option>
                }
            </select>

        </div>
        <div class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
            <span class="label-control input-sm" id="FieldName">@item.Name</span>
            <input type="hidden" id="fieldDataType" value="@((int)item.DataType)" />
        </div>
        <div class="form-group col-md-2" style="margin-bottom: 1px !important;padding-left: 1px !important;">
            <select class="form-control input-sm" id="Operator">
                @{
                var listOperator = ArchiveMVC5.Utility.GeneratorJson.GetOperatorFromType(item.DataType);

                foreach (Ecm.Domain.SearchOperator oper in listOperator)
                {
                    <option value="@((int)oper)">@oper</option>
                }
                }
            </select>
        </div>
        <div class="form-group col-md-5" style="margin-bottom: 1px !important;padding-left: 1px !important;" id="@item.Id"> @*id="@idComboboxValue">*@
            @Html.Raw(ArchiveMVC5.Utility.GeneratorJson.GetComboBoxValue(item, listOperator.FirstOrDefault(), value1, value2))
        </div>
        <div class="form-group col-md-1" style="margin-bottom: 1px !important; padding-left: 0px !important">
            <span></span>
        </div>
    </div>
    }
}

ArchiveMVC5/Views/Search/ComposeMail.cshtml
@model ArchiveMVC5.Models.SaveOption

<div class="box box-info">
    <div class="box-body" id="mail_div">
        <div class="form-group">
            <input type="text" placeholder="To:" class="form-control input-sm col-md-10" id="mail_to" />
            @if (Model.CC == null)
            {
                <a id="show_cc"><span class="lable label-success col-md-1">Mail CC</span></a>
            }
            @if (Model.BCC == null)
            {
                <a id="show_bcc"><span class="lable label-success col-md-1">Mail BCC</span></a>
            }
        </div>
        @if (Model.CC != null && Model.CC.Count > 0)
        {
            <div class="form-group">
                <input type="text" placeholder="Cc:" class="form-control input-sm" id="mail_cc" value="@Model.CC"/>
            </div>
        }
        @if (Model.BCC != null && Model.BCC.Count > 0)
        {
            <div class="form-group">
                <input type="text" placeholder="Bcc:" class="form-control input-sm" id="mail_bcc" value="@Model.BCC"/>
            </div>
        }
        <div class="form-group">
            <input type="text" placeholder="Subject:" class="form-control input-sm" id="mail_subject" value="@Model.Subject"/>
        </div>
        <div class="form-group">
            <textarea class="textarea" id="mail_body" placeholder="Place some text here"></textarea>
        </div>
    </div>
    <div class="box-footer">
        <div class="btn-group">
            <button class="btn btn-info" id="btn_send">
                <i class="fa fa-envelope"></i>
                <span>Send</span>
            </button>
        </div>
        <div class="btn-group">
            <button class="btn btn-info" id="btn_discard">
                <i class="fa fa-times"></i>
                <span>Discard</span>
            </button>
        </div>
    </div>
</div>

ArchiveMVC5/Views/Search/CreateAdvanceSearchFromQuery.cshtml
@model ArchiveMVC5.Models.SearchModel
@{

    var _script = "";
}

       @* @foreach (var item in Model.ListQueryModel.Where(p=>p.Id == Model.QueryId ).FirstOrDefault().SearchQueryExpressions.Where(p=>p.Field != null).Select(p=>p)) *@
        @foreach (var item in Model.ListQueryModel.Where(p => p.Id == Model.QueryId).FirstOrDefault().SearchQueryExpressions.Where(p => p.Field != null).Select(p => p))
        {
           
            var idComboboxValue = ArchiveMVC5.Utility.UniqueId.GetUniqueKey();
            <div id="RowCondition" value="@item.Id">
                <div>
                    <div class="input-control select">                       
                        <select id="Conjunction">
                            @foreach (Ecm.Domain.SearchConjunction dataType in Enum.GetValues(typeof(Ecm.Domain.SearchConjunction)))
                            {
                                
                                <option value="@((int)dataType)" @(item.Condition==dataType?"selected":"")>@dataType.ToString()</option>
                            }  
                            
                           
                        </select>
                    </div>
                </div>
                <div>
                    <div class="display_lable">
                       <span id="FieldName" value="@(item.Field.Id)">@item.Field.Name</span>
                    </div>
                </div>
                <div>
                    <div class="input-control select">
                        <select id="Operator" onchange="CreateTextBoxValue(this.value,'@(item.Field.Id)','@idComboboxValue')">
                            @{
                                if(item.Field.DataType == Ecm.Domain.FieldDataType.Date)
                                {
                                    _script += "$('[id=\"" + idComboboxValue + "\"]').find('input').datepicker();";
                                }
                                var listOperator = ArchiveMVC5.Utility.GeneratorJson.GetOperatorFromType(item.Field.DataType);
                            }
                            @foreach (var item1 in listOperator)
                            {                                
                                <option value="@((int)item1)" @(item.Operator==item1?"selected":"")>@item1</option>
                            }  
                            
                        </select>

                    </div>
                </div>
                <div id="@idComboboxValue" class="search_input">
                    @Html.Raw(ArchiveMVC5.Utility.GeneratorJson.GetComboBoxValue(item.Field.DataType, item.Operator, item.Value1, item.Value2))
                </div>
                <div>
                </div>
            </div>    
        }
        
        
    
<script>
    @Html.Raw(_script);
</script>

ArchiveMVC5/Views/Search/Index.cshtml
@model  ArchiveMVC5.Models.SearchModel
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_SearchLayout.cshtml";
}

@section AddToHead
    {

    @Styles.Render("~/Content/tablesorter/style.css")

    @Styles.Render("~/Content/Search.css")
    <script>
        URL_MenuOpen = "@Url.Content("~/Images/appbar.book.open.png")";
        URL_MenuPrint = "@Url.Content("~/Images/button/control/printer_select.png")";
        URL_MenuEmail = "@Url.Content("~/Images/button/control/send_mail_select.png")";
        URL_MenuDownload = "@Url.Content("~/Images/button/control/save_select.png")";
        URL_MenuDelete = "@Url.Content("~/Images/appbar.delete.png")";
    </script>

    @Scripts.Render("~/Scripts/jquery.tablesorter.min.js")
    @Scripts.Render("~/Scripts/calendar.js")
    @Scripts.Render("~/Scripts/moment.js")
    @Scripts.Render("~/Scripts/moment_langs.js")
    @Scripts.Render("~/Scripts/popup.js")
    @Scripts.Render("~/Scripts/load.js")
    @Scripts.Render("~/Scripts/ContextMenu/jquery.contextMenu.js")

    <script>
        var firstIDDocType = "@Model.DocTypeIDFirst";
        var URL_SaveQuery = "@Url.Action("SaveQuery", "Search")";
        var URL_GetSaveQueryName = "@Url.Action("GetSaveQueryName", "Search")";
        var URL_DeteleQuery = "@Url.Action("DeteleQuery", "Search")";
        var URL_QueryExisted = "@Url.Action("QueryExisted", "Search")";
        var URL_RunGlobalSearch = "@Url.Action("RunGlobalSearch", "Search")";
        var URL_RunAdvanceSearch = "@Url.Action("RunAdvanceSearch", "Search")";
        var URL_RunSearchDocumentType = "@Url.Action("RunSearchDocumentType", "Search")";
        var URL_RunContentSearch = "@Url.Action("RunContentSearch", "Search")";
        var URL_CreateSearchQueries = "@Url.Action("CreateSearchQueries", "Search")";
        var URL_CreateSearchConditionFromQueries = "@Url.Action("CreateSearchConditionFromQueries", "Search")";
        var URL_AddMoreCondition = "@Url.Action("AddMoreCondition", "Search")";
        var URL_CreateOperator = "@Url.Action("CreateOperator", "Search")";
        var URL_CreateTextBoxValue = "@Url.Action("CreateTextBoxValue", "Search")";
        var URL_CreateAdvanceSearchFromQuery = "@Url.Action("CreateAdvanceSearchFromQuery", "Search")";
        var URL_Order = "@Url.Action("Order", "Search")";
        var URL_Delete = "@Url.Action("Delete", "Search")";
        var URL_LoadSearchValueControl = "@Url.Action("GetAdvanceSearchValues", "Search")";
        var CacheDocType = "@Html.Raw(Model.CacheDocType)";
        
        var URL_EditDocID = "@Url.Action("Index", "View")?id=";
        @{
            var sa = new Dictionary<int, String>();
            foreach (Ecm.Domain.FieldDataType dataType in Enum.GetValues(typeof(Ecm.Domain.FieldDataType)))
            {
                sa.Add((int)dataType, dataType.ToString());


            }
            }
       
        var DataType = @Html.Raw(Model.DataTypeJson);
        
        var DataType_Item = @Html.Raw(Model.DataTypeItemJson);
        var DocType = @Html.Raw(Model.DocTypeJson);
        var Conjunction = @Html.Raw(Model.ConjunctionJson);
        var QueryNameFirst = @Html.Raw(Model.QueryNameFirst);

        
    </script>
}

<!-- body here -->
<section>
    <!-- documenttype nav -->
    <!--Ket thuc documenttype nav -->
    <!-- search -->
        <!-- Search Query -->
        <div class="box">
            <div class="form_query_search">
                <div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="box" style="margin: 0px">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Advance Search</h3>
                                    <div class="box-tools pull-right">
                                        <button class="btn btn-box-tool" data-widget='collapse' data-toggle="tooltip" title="Collapse" aria-expanded="false"><i class="fa fa-minus"></i></button>
                                    </div>
                                </div>
                                <!-- Search conditions -->
                                <div class="box-body layout_table">
                                </div>
                                <div class="box-footer clearfix">
                                    <!-- Search buttons-->
                                    <div class="col-md-12 btn-group">
                                        <button class="btn bg-olive btn-sm margin col-md-1.5 bt_add_conditions" type="button"><i class="glyphicon glyphicon-plus"></i> Add condition </button>
                                        <button class="btn bg-olive btn-sm margin col-md-1.5 bt_reset_conditions" type="button"><i class="fa fa-undo"></i> Reset condition </button>
                                        <a class="btn bg-olive btn-sm margin col-md-1.5 bt_save_query"><i class="glyphicon glyphicon-save"></i> Save as query </a>
                                        <a class="btn bg-olive btn-sm margin col-md-1.5 bt_delete_query"><i class="glyphicon glyphicon-trash"></i> Delete query </a>
                                        <button class="btn bg-olive btn-sm margin col-md-1.5 bt_search" type="button"><i class="glyphicon glyphicon-search"></i> Search </button>
                                        <button class="btn bg-olive btn-sm margin col-md-1.5 bt_search_content" type="button" style="display:none"><i class="glyphicon glyphicon-search"></i> Search content </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box">
            <div class="datagript_result">
            </div>
        </div>
        <!-- /.modal -->
        <div class="modal" id="saveQuery">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title">Save query information</h4>
                    </div>
                    <div class="modal-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <span class="control-label">Query name</span><span class="required">*</span>
                                <input class="form-control input-sm" type="text" id="queryName" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn bg-olive btn-sm" type="button" data-dismiss="modal">Close</button>
                        <button class="btn bg-olive btn-sm" type="button" id="btSaveQuery">Save changes</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <div class="modal" id="deleteQuery">
            <div class="modal-dialog" id="confirm-modal">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title">Delete query confirmation!</h4>
                    </div>
                    <div class="modal-body">
                        <i class='glyphicon glyphicon-info-sign'></i>
                        <h4>Are you sure you want to delete selected query? </h4>
                    </div>
                    <div class="modal-footer">
                        <button class="btn bg-olive btn-sm" type="button" data-dismiss="modal">Cancel </button>
                        <button class="btn bg-olive btn-sm" type="button" id="btDeleteQuery">OK </button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
</section>
<!-- Ket thuc section -->

@*@RenderPage("../Shared/Menu.cshtml")*@
<div id="dialog_send_mail" class="modal padding-5" data-controls-modal="dialog_lookup" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header padding-5">
                <h3>Send mail</h3>
            </div>
            <div class="modal-body padding-5">
                <div class="box box-info">
                    <div class="box-body" id="mail_div">
                        <div class="form-group">
                            <input type="text" placeholder="To:" class="form-control input-sm col-md-8" id="mail_to" />
                            <a id="show_cc" class="btn btn-sm">Show cc</a>
                            <a id="show_bcc" class="btn btn-sm">Show bcc</a>
                        </div>
                        <div class="form-group" id="div_cc">
                            <input type="text" placeholder="Cc:" class="form-control input-sm" id="mail_cc" value="" />
                        </div>
                        <div class="form-group" id="div_bcc">
                            <input type="text" placeholder="Bcc:" class="form-control input-sm" id="mail_bcc" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" placeholder="Subject:" class="form-control input-sm" id="mail_subject" value="test" />
                        </div>
                        <div class="form-group">
                            <textarea class="textarea form-control" id="mail_body" placeholder="Place some text here"></textarea>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <div class="btn-group">
                                <button class="btn btn-sm bg-olive" id="btn_send">
                                    <i class="glyphicon glyphicon-send"></i>
                                    <span>Send</span>
                                </button>
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-sm bg-olive" id="btn_discard" data-dismiss="modal">
                                    <i class="fa fa-times"></i>
                                    <span>Discard</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $("#mail_body").wysihtml5({
        "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
        "emphasis": true, //Italics, bold, etc. Default true
        "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
        "html": false, //Button which allows you to edit the generated HTML. Default false
        "link": true, //Button to insert a link. Default true
        "image": true, //Button to insert an image. Default true,
        "color": true, //Button to change color of font  
        "blockquote": true, //Blockquote  
        "size": "sm", //default: none, other options are xs, sm, lg
        "fa": true
    });
</script>

ArchiveMVC5/Views/Search/SearchByContent.cshtml
@model ArchiveMVC5.Models.SearchResultModel

@{
    ViewBag.Title = "SearchByContent";
}

<h2>SearchByContent</h2>